[package]
name = "project-euler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
math = { path = "../../packages/math" }

[[bin]]
name = "project-euler"
path = "src/main.rs"
